### ISSUE TITLE
Specify FreeImage version dependencies in the README

### ISSUE THREAD

**Issue by changa** [cfis/free-image-ruby#3]
Hi,

It seems that free-image-ruby needs a FreeImage version > 3.10 since it works fine on my Debian testing development computer (with libfreeimage-dev-3.15.1-1) but fails on the Debian stable pre-production server with version 3.10.0-4.

(The error message reads `Function 'FreeImage_HasPixels' not found in [/usr/lib64/libfreeimage.so]`.)

I really think a mention of the minimal FreeImage library version would be most helpful.

**Comment by cfis** [comment]
Fixed.
