### ISSUE TITLE
image composite

### ISSUE THREAD

**Issue by rawsyntax** [cfis/free-image-ruby#4]
In cookbook, there's no example of how to do an image composite -- say for a watermark or something.

I've got code like:
```ruby
wm = FreeImage::Bitmap.open(@watermark)
img = FreeImage::Bitmap.open(@file)
wm.composite(img)
wm.save(File.join(APP_ROOT, 'done.png'), :png)
```

but I get 
`FreeImage::Error: Cannot create a bitmap from a null pointer`

Is composite working -- or does only composite_with_color work?

**Comment by cfis** [comment]
The watermark has to be the same size as the main image.  I added a test for this and an example in the cookbook.
