### ISSUE TITLE
Problems creating an RGBQuad

### ISSUE THREAD

**Issue by jonelf** [cfis/free-image-ruby#7]
white = FreeImage::RGBQuad.create(255, 255, 255)
white.to_s
=> "RGBQuad - Red: 0, Green: 0, Blue: 255, Alpha: 0"

I expected
=> "RGBQuad - Red: 255, Green: 255, Blue: 255, Alpha: 0"

free-image (0.6.2)

**Comment by cfis** [comment]
Try the latest version (0.7.0), this appears to work as expected.

**Comment by jonelf** [comment]
Confirmed!
