### ISSUE TITLE
Document the ability to set custom JPEG quality level

### ISSUE THREAD

**Issue by Wardrop** [cfis/free-image-ruby#8]
Could you please document (perhaps under AbstractSource::Encoder) the fact you can pass any value between 1 and 100 in the flags parameter when saving as JPEG to set a custom quality level. I only found this out from extensive googling on the FreeImage library.

``` ruby
image.save("./thumbnail.jpg", :jpeg, 90)
```
Cheers

**Comment by cfis** [comment]
Happy to accept a patch to the documentation if you have one.

**Comment by cfis** [comment]
Actually, this appears documented.  See 
http://cfis.github.io/free-image-ruby/classes/FreeImage/File.html#method-i-save

And here:

http://cfis.github.io/free-image-ruby/classes/FreeImage/AbstractSource/Encoder.html

**Comment by Wardrop** [comment]
No that only documents the constants. It seems like you can only choose from a handful of predefined image quality levels (e.g. JPEG_QUALITYSUPERB, JPEG_QUALITYGOOD, JPEG_QUALITYNORMAL). The difference in quality and file size between JPEG_QUALITYSUPERB and JPEG_QUALITYGOOD is huge, and most people will want something between the two.

FreeImage allows you to use any JPEG quality value between 0 and 100. It reserves the first 7 bits of the JPEG flag parameter for this purpose. If you wanted to just set the quality to 90 like the example in my OP, you can do just that. If you want to set the quality to 90 and JPEG_OPTIMIZE, you could just do this:

``` ruby
image.save("./thumbnail.jpg", :jpeg, 90 | FreeImage::AbstractSource::Encoder::JPEG_OPTIMIZE)
```

I'll make a patch for the documentation.

**Comment by cfis** [comment]
Ah, I see.  Thanks, request merged.
