### ISSUE TITLE
RangeError when calling Bitmap.open with IO object

### ISSUE THREAD

**Issue by Wardrop** [cfis/free-image-ruby#9]
I'm attempting to open an image from an IO stream (File object in this case), but I get the following error:

  RangeError: integer 70353457099240 too big to convert to `int'
	from /Users/tomwardrop/.rvm/gems/ruby-2.1.5/gems/free-image-0.6.2/lib/free-image/sources/io.rb:78:in `put_int32'

The cause is that a Ruby fixnum (which Ruby's Object#object_id returns) can be up to 62 bits, where as a C integer has a maximum length of 32 bits. I believe the following line needs to be changed to use a *long* instead of an *int*: https://github.com/cfis/free-image-ruby/blob/master/lib/free-image/sources/io.rb#L77

**Comment by Wardrop** [comment]
I made pull request #10 with a fix that works for me.

**Comment by cfis** [comment]
Fixed via your pull request.  Thanks!
